### ISSUE TITLE
End point dead

### ISSUE THREAD

**Issue by mrx23dot** [izavits/monero-price#1]
https://api.coinmarketcap.com/v1/ticker/monero/..

{"code": "410 Gone", "reason": "We no longer serving this endpoint here" }

**Comment by izavits** [comment]
Thanks! It seems like coinmarketcap API has changed. From a quick search, it seems that this is free: https://min-api.cryptocompare.com/data/price?fsym=XMR&tsyms=BTC,USD,EUR
I'll give it a try as soon as I find some free time.

**Comment by izavits** [comment]
OK, I have changed it to use the above API. Hope it works again not.

Connects to: https://github.com/izavits/monero-price/commit/4588315af170d03c1578253eab4e19d296b54047
